config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :flats
  resources :lands do
    collection { post :import }
  end

  get '/robots.:format' => 'pages#robots'
  get "sitemap.xml" => "sitemaps#index", :format => "xml", :as => :sitemap

  

  mount Attachinary::Engine => "/attachinary"

end

app/models/comparative.rb
class Comparative < ActiveRecord::Base
  belongs_to :flat
end

app/models/flat.rb
class Flat < ActiveRecord::Base
  has_many :comparatives
  has_attachments :photos, maximum: 3

  geocoded_by :full_street_address
  after_validation :geocode, if: :address_changed?


  def full_street_address
    [address, city].compact.join(', ')
  end




end

app/models/land.rb
class Land < ActiveRecord::Base

	extend FriendlyId
	friendly_id :address_complete, use: :slugged

	def self.import(file)
    	CSV.foreach(file.path, headers: true) do |row|
      		Land.create! row.to_hash
     	end
  	end

  	def address_complete
  		[:address, :city]
  	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  	def default_url_options
  		{ host: ENV['HOST'] || 'localhost:3000' }
	end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "",
               template: 'flats/show.pdf.erb',
               layout: 'layouts/pdf.html.erb',  # layout used
               show_as_html: params[:debug].present?
      end
    end
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end




  def flat_params
  params.require(:flat).permit(
      :first_name,
      :last_name,
      :surface_land,
      :surface_habitation,
      :common_wall,
      :rooms,
      :bedroom,
      :bathroom,
      :surface_carrez,
      :year_construction,
      :latitude,
      :longitude,
      :address,
      :city,
      photos: [])
  end



end

app/controllers/lands_controller.rb
class LandsController < ApplicationController
	def index
		@lands = Land.all
	end

	def show
		@land = Land.friendly.find(params[:id])
	end

	def new
		@land = Land.new
	end

	def import
  		Land.import(params[:file])
  		redirect_to lands_path, notice: "Lands addes succesfully"
	end

	def create
		@land = Land.friendly.find(land_params)
		if @land.save
			redirect_to land_path(@land)
		else
			render :new
		end
	end

	def land_params
  		params.require(:land).permit(
      	:address,
      	:neighborhood,
      	:city,
      	:slug
      	)
  	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  	def robots
  		respond_to :text
  		expires_in 6.hours, public: true
	end

	def sitemap
	    @flats = Flat.all
	    respond_to do |format|
	        format.xml { render layout: false }
	        format.txt { render layout: false }
	    end
	end

	
end

app/controllers/sitemaps_controller.rb
class SitemapsController < ApplicationController
  def index
    @static_pages = [root_url]

    @lands = Land.all
    

    respond_to do |format|
      format.xml
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/lands_helper.rb
module LandsHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META['meta_title']
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META['meta_description']
  end

  
end

app/views/flats/new.html.erb
<%= simple_form_for @flat do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :address %>
  <%= f.input :surface_land %>
  <%= f.input :surface_habitation %>
  <%= f.input :surface_carrez %>
  <%= f.input :common_wall %>
  <%= f.input :rooms %>
  <%= f.input :bedroom %>
  <%= f.input :bathroom %>
  <%= f.input :year_construction %>
  <%= f.input :photos, as: :attachinary %>
  <%= f.button :submit %>
<% end %>

app/views/flats/show.html.erb
<% @flat.photos.each do |photo| %>
  <%= cl_image_tag photo.path, width: 300, height: 200, crop: :fill %>
<% end %>

app/views/flats/show.pdf.erb
<div class="page">
  <h1> 1. Fiche d'identité de votre maison </h1>
  <hr>
  <div class="text-center">


  </div>
  <div class="container">
    <div class="row">
      <div class='col-xs-12'>
        <div class="address text-center">
        <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?key=AIzaSyCwCp3To_EfAyq9Yt0-x9O2KfQMU4dLRw8&zoom=15&size=600x300&sensor=false&maptype=roadmap&markers=color:red|#{@flat.full_street_address}", class: "item-show-map" %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-5">
        <h4>propriétaire(s)</h4>
      </div>
      <div class="col-xs-5">
        <h4><%= @flat.first_name %> <%= @flat.last_name %></h4>
      </div>
    </div>
    <% if @flat.surface_land.present? %>
      <div class="row">
        <div class="col-xs-5">
          <h4>Surface du terrain</h4>
        </div>
        <div class="col-xs-5">
          <h4><%= @flat.surface_land %>  m²</h4>
        </div>
      </div>
    <% end %>
    <% if @flat.surface_habitation.present? %>
      <div class="row">
        <div class="col-xs-5">
          <h4>Surface habitable</h4>
        </div>
        <div class="col-xs-5">
          <h4><%= @flat.surface_habitation %>  m²</h4>
        </div>
      </div>
    <% end %>
    <% if @flat.common_wall.present? %>
      <div class="row">
        <div class="col-xs-5">
          <h4>Nb. murs mitoyens</h4>
        </div>
        <div class="col-xs-5">
          <h4><%= @flat.common_wall %>  </h4>
        </div>
      </div>
    <% end %>
    <% if @flat.rooms.present? %>
      <div class="row">
        <div class="col-xs-5">
          <h4>Nb. de pièces</h4>
        </div>
        <div class="col-xs-5">
          <h4><%= @flat.rooms %>  pièces</h4>
        </div>
      </div>
    <% end %>
    <% if @flat.bedroom.present? %>
      <div class="row">
        <div class="col-xs-5">
          <h4>Nb. de chambre</h4>
        </div>
        <div class="col-xs-5">
          <h4><%= @flat.bedroom %>  </h4>
        </div>
      </div>
    <% end %>
    <% if @flat.bathroom.present? %>
      <div class="row">
        <div class="col-xs-5">
          <h4>Salle(s) de bains</h4>
        </div>
        <div class="col-xs-5">
          <h4><%= @flat.bathroom %>  </h4>
        </div>
      </div>
    <% end %>
    <% if @flat.year_construction.present? %>
      <div class="row">
        <div class="col-xs-5">
          <h4>Année de construction</h4>
        </div>
        <div class="col-xs-5">
          <h4><%= @flat.year_construction %>  </h4>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="page">
  <h4><%= @flat.first_name %> <%= @flat.last_name %></h4>
</div>

app/views/lands/index.html.erb
<% @lands.each do |land| %>
	<%= link_to land.address, land %>
	<%= land.neighborhood %>
	<%= land.city %>
<% end %>

app/views/lands/show.html.erb
<% content_for :meta_title, "estimer votre bien immobilier à #{@land.address} , #{@land.city} €" %>
<% content_for :meta_description, @land.address %>


<h1> Votre estimation immobilière au <%= @land.address %> <%= @land.city %> </h1>

<%= @land.address %>
<%= @land.neighborhood %>
<%= @land.city %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <!-- Google+ Schema.org markup -->
    <meta itemprop="name" content="<%= meta_title %>">
    <meta itemprop="description" content="<%= meta_description %>">
    
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?sensor=false&key=AIzaSyCwCp3To_EfAyq9Yt0-x9O2KfQMU4dLRw8" %>
    <%= javascript_include_tag "https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places" %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8' >
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700|Lato:100,300,400,100italic|Raleway:300,400' rel='stylesheet' type='text/css'>
    <%= wicked_pdf_stylesheet_link_tag "pdf" %>
  </head>
  <body>
    <div class="container">
    <%= yield %>
    </div>
    <footer>

    </footer>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Estimer votre bien immobilier</h1>
<p>Sur Saint Maur Des Fossés</p>

<h3>Import Lands</h3>
	<%= form_tag import_lands_path, multipart: true do %>
  		<%= file_field_tag :file %>
  		<%= submit_tag "Upload lands" %>
	<% end %>

app/views/pages/robots.txt.erb
<% if Rails.env.production? %>
  User-Agent: *
  Allow: /
  Disallow: /admin
  Sitemap: http://www.votre-estimation.com/sitemap.xml
<% else %>
  User-Agent: *
  Disallow: /
<% end %>

app/views/pages/sitemap.text.erb
<% for flat in @flats do %>
<%= flat_url(flat) %>
<% end %>